name: Electron Forge CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Use Node.js 22.4
      uses: actions/setup-node@v4
      with:
        node-version: '22.4'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Package application
      run: pnpm run package

    # - name: Run tests
    #   uses: coactions/setup-xvfb@v1
    #   with:
    #     run: pnpm test:e2e:raw

    - name: Make distributable
      if: success()
      run: pnpm run make --skip-package

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: out/make/**/*

  release:
    permissions:
      contents: write
      discussions: write
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Use Node.js 22.4
      uses: actions/setup-node@v4
      with:
        node-version: '22.4'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Publish release
      run: pnpm run electron-forge publish --from-dry-run

    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: |
    #       artifacts/**/*
    #     draft: true
    #     prerelease: true
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
