name: Electron Forge CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Package application
      run: pnpm run package

    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: pnpm test:e2e:raw

    - name: Make distributable
      if: success()
      run: pnpm run make --skip-package

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: out/make/**/*

  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/**/*
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
